# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- draft

pool:
  vmImage: 'ubuntu-20.04'

jobs:
- job: native
  steps:
  - script: ./configure --tests
    displayName: Configure

  - script: make
    displayName: Build

  - script: go get -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run
    displayName: Get Deps

  - script: |
      export GOBIN=$HOME/go/bin
      go install -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run
      export PATH=$GOBIN:$PATH

      ./t
    displayName: Test

- job: docker
  steps:

  - script: docker build .
    displayName: Build
