#!/bin/sh
set -e

# export KUNGFU_CONFIG_LOG_LEVEL=debug

rebuild() {
    cd src/stdml/collective/elastic
    make
    cd -
    ./configure --enable-elastic #--verbose
    make -j $(nproc)
}

kungfu_run_flags() {
    echo -q
    echo -logdir logs
    echo -logfile kungfu-run.log

    echo -np 2

    echo -port 7777

    echo -w
    local port=9999
    echo -config-server http://127.0.0.1:$port/config
    echo -builtin-config-port $port
}

kungfu_run() {
    kungfu-run $(kungfu_run_flags) $@
}

rebuild

kungfu_run ./bin/example-elastic
