#!/bin/sh
set -e

. ./scripts/profile/measure.sh
. ./scripts/bin/stdml-collective-run

# export KUNGFU_CONFIG_LOG_LEVEL=debug

rebuild() {
    cd src/stdml/collective/elastic
    make
    cd -
    ./configure --enable-elastic #--verbose
    make -j $(nproc)
}

app_flags() {
    echo --max-step=10
    echo '1:2'
    echo '3:1'
    echo '5:4'
    echo '7:1'
}

trace() {
    echo "BEGIN $@"
    $@
    echo "END $@"
    echo
    echo
}

measure rebuild

rm -fr logs/elastic
trace stdml_collective_elastic_run_n 1 ./bin/example-elastic $(app_flags)
trace stdml_collective_elastic_run_n 1 ./bin/example-elastic-state $(app_flags)
