#!/bin/sh
set -e

. ./kungfu-launcher.sh

cfg_flags() {
    true
    echo --verbose
    echo --shared
}

rebuild() {
    if [ ! -f Makefile ]; then
        ./configure $(cfg_flags)
    fi
    make -j $(nproc)
}

elastic_flags() {
    echo --max-step=10
    echo '1:2'
    echo '3:1'
    echo '5:4'
    echo '7:1'
}

trace rebuild

export STDML_COLLECTIVE_ENABLE_LOG=1

prun 2 ./bin/example-collective

# prun 1 ./bin/test-broadcast
# prun 2 ./bin/test-broadcast

# prun 2 ./bin/example-1

# erun 1 ./bin/example-elastic-state $(elastic_flags)
