name: CI

on:
- push

jobs:
  build:

    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: go get -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run
    - run: go install -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run

    - run: ./configure
    - run: make
    - run: |
        export PATH=/root/go/bin:${PATH}
        ./scripts/run/example-1.sh
