name: CI

on:
- push

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: go get -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run

    - run: ./configure --tests
    - run: make
    - run: |
        export GOBIN=$HOME/go/bin
        go install -v github.com/lsds/KungFu/srcs/go/cmd/kungfu-run
        export PATH=$GOBIN:$PATH

        # ./scripts/run/example-1.sh
        ./t

  mpi:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: sudo apt install -y openmpi-bin

    - run: ./configure --mpi
    - run: make
    - run: ./scripts/run/example-mpi.sh

  release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - run: ./configure --release=$(git rev-parse --short HEAD) --deb --shared --disable-cxx11-abi
    - run: make
    - run: make package

    - uses: actions/upload-artifact@v2
      with:
        name: libstdml-collective
        path: |
          release/stdml-collective-*-Linux.tar.gz
          release/stdml-collective-*-Linux.deb
